import type { MealRecipe, MealType } from "@/research/types";

const breakfasts: MealRecipe[] = [
  {
    mealType: "breakfast",
    name: "Quinoa Berry Bowl",
    description: "Fluffy quinoa topped with mixed berries and cinnamon.",
    calories: 380,
    prepTime: 15,
    servings: 1,
    tags: ["High-Fiber", "Energizing"],
    allergens: [],
    diets: ["vegan", "vegetarian"],
    ingredients: ["1 cup cooked quinoa", "1/2 cup mixed berries", "1 tbsp maple syrup", "1/4 tsp cinnamon"],
    instructions: ["Cook quinoa.", "Top with berries and cinnamon.", "Drizzle maple syrup and serve."],
  },
  {
    mealType: "breakfast",
    name: "Avocado Tomato Toast",
    description: "Whole grain toast with avocado, tomatoes, and lemon.",
    calories: 350,
    prepTime: 10,
    servings: 1,
    tags: ["Quick", "Heart-Healthy"],
    allergens: ["gluten", "wheat"],
    diets: ["vegetarian", "mediterranean"],
    ingredients: ["2 slices whole grain bread", "1 ripe avocado", "1/2 cup cherry tomatoes", "1 tsp lemon juice"],
    instructions: ["Toast bread.", "Mash avocado with lemon.", "Assemble and serve."],
  },
  {
    mealType: "breakfast",
    name: "Greek Yogurt Parfait",
    description: "Greek yogurt layered with berries and granola.",
    calories: 320,
    prepTime: 8,
    servings: 1,
    tags: ["Protein-Rich", "Probiotic"],
    allergens: ["dairy", "gluten"],
    diets: ["vegetarian"],
    ingredients: ["1 cup Greek yogurt", "1/3 cup granola", "1/2 cup berries"],
    instructions: ["Layer yogurt, granola, and berries.", "Serve immediately."],
  },
  {
    mealType: "breakfast",
    name: "Veggie Omelette",
    description: "Egg omelette with peppers, onions, and spinach.",
    calories: 290,
    prepTime: 20,
    servings: 1,
    tags: ["Protein-Rich", "Low-Carb"],
    allergens: ["eggs"],
    diets: ["lowcarb", "highprotein", "vegetarian"],
    ingredients: ["3 eggs", "1 cup spinach", "1/4 cup peppers", "1/4 cup onions"],
    instructions: ["Sauté veggies.", "Add beaten eggs.", "Fold and cook until set."],
  },
  {
    mealType: "breakfast",
    name: "Chia Pudding",
    description: "Overnight chia with vanilla and berries.",
    calories: 340,
    prepTime: 5,
    servings: 1,
    tags: ["Make-Ahead", "High-Fiber"],
    allergens: ["nuts"],
    diets: ["vegan", "vegetarian"],
    ingredients: ["3 tbsp chia seeds", "1 cup almond milk", "1/2 tsp vanilla", "1/2 cup berries"],
    instructions: ["Mix chia, milk, and vanilla.", "Chill overnight.", "Top with berries."],
  },
];

const lunches: MealRecipe[] = [
  {
    mealType: "lunch",
    name: "Mediterranean Chickpea Salad",
    description: "Chickpeas, cucumber, tomato, olive oil, and herbs.",
    calories: 420,
    prepTime: 15,
    servings: 1,
    tags: ["Mediterranean", "High-Fiber"],
    allergens: [],
    diets: ["vegan", "vegetarian", "mediterranean"],
    ingredients: ["1 cup chickpeas", "1/2 cup cucumber", "1/2 cup tomato", "1 tbsp olive oil", "Lemon"],
    instructions: ["Combine ingredients.", "Dress with olive oil and lemon.", "Season to taste."],
  },
  {
    mealType: "lunch",
    name: "Chicken & Quinoa Bowl",
    description: "Lean chicken, quinoa, greens, and tahini.",
    calories: 520,
    prepTime: 25,
    servings: 1,
    tags: ["High-Protein", "Balanced"],
    allergens: ["sesame"],
    diets: ["highprotein"],
    ingredients: ["4 oz chicken breast", "3/4 cup cooked quinoa", "2 cups greens", "1 tbsp tahini"],
    instructions: ["Cook chicken.", "Assemble bowl.", "Drizzle tahini and serve."],
  },
  {
    mealType: "lunch",
    name: "Tofu Veggie Stir-Fry",
    description: "Tofu with mixed veggies over cauliflower rice.",
    calories: 460,
    prepTime: 25,
    servings: 1,
    tags: ["Low-Carb", "Plant-Protein"],
    allergens: ["soy"],
    diets: ["vegan", "vegetarian", "lowcarb", "highprotein"],
    ingredients: ["Tofu", "Broccoli", "Bell peppers", "Garlic", "Cauliflower rice"],
    instructions: ["Sauté veggies.", "Add tofu and seasoning.", "Serve over cauliflower rice."],
  },
  {
    mealType: "lunch",
    name: "Tuna & White Bean Salad",
    description: "Tuna with beans, parsley, lemon, and olive oil.",
    calories: 480,
    prepTime: 12,
    servings: 1,
    tags: ["High-Protein", "Quick"],
    allergens: ["fish"],
    diets: ["pescatarian", "highprotein", "mediterranean"],
    ingredients: ["1 can tuna", "1/2 cup white beans", "1 tbsp olive oil", "Lemon", "Parsley"],
    instructions: ["Combine tuna and beans.", "Dress with olive oil and lemon.", "Season and serve."],
  },
];

const dinners: MealRecipe[] = [
  {
    mealType: "dinner",
    name: "Salmon + Roasted Vegetables",
    description: "Salmon with zucchini and carrots.",
    calories: 560,
    prepTime: 30,
    servings: 1,
    tags: ["Omega-3", "High-Protein"],
    allergens: ["fish"],
    diets: ["pescatarian", "highprotein", "mediterranean", "lowcarb"],
    ingredients: ["6 oz salmon", "2 cups veggies", "1 tbsp olive oil", "Salt", "Pepper"],
    instructions: ["Roast veggies.", "Bake salmon.", "Serve together."],
  },
  {
    mealType: "dinner",
    name: "Turkey Lettuce Wraps",
    description: "Ground turkey with veggies in lettuce cups.",
    calories: 510,
    prepTime: 25,
    servings: 1,
    tags: ["Low-Carb", "High-Protein"],
    allergens: [],
    diets: ["lowcarb", "highprotein"],
    ingredients: ["5 oz ground turkey", "Lettuce leaves", "Onion", "Garlic", "Spices"],
    instructions: ["Cook turkey with aromatics.", "Spoon into lettuce cups.", "Serve."],
  },
  {
    mealType: "dinner",
    name: "Lentil Vegetable Stew",
    description: "Hearty lentils with carrots, celery, and herbs.",
    calories: 490,
    prepTime: 40,
    servings: 2,
    tags: ["High-Fiber", "Comfort"],
    allergens: [],
    diets: ["vegan", "vegetarian", "mediterranean"],
    ingredients: ["1 cup lentils", "Carrots", "Celery", "Onion", "Garlic", "Herbs"],
    instructions: ["Sauté aromatics.", "Simmer lentils until tender.", "Season and serve."],
  },
  {
    mealType: "dinner",
    name: "Cauliflower Rice Burrito Bowl",
    description: "Cauli rice with beans, salsa, and avocado.",
    calories: 520,
    prepTime: 20,
    servings: 1,
    tags: ["Low-Carb", "Fiber"],
    allergens: ["nightshades"],
    diets: ["vegan", "vegetarian", "lowcarb"],
    ingredients: ["Cauliflower rice", "Black beans", "Salsa", "Avocado", "Lime"],
    instructions: ["Warm beans.", "Assemble bowl.", "Top with salsa and avocado."],
  },
];

const snacks: MealRecipe[] = [
  {
    mealType: "snack",
    name: "Apple + Peanut Butter",
    description: "Apple slices with peanut butter.",
    calories: 190,
    prepTime: 5,
    servings: 1,
    tags: ["Portable", "Fiber"],
    allergens: ["peanuts"],
    diets: ["vegetarian"],
    ingredients: ["1 apple", "2 tbsp peanut butter"],
    instructions: ["Slice apple.", "Dip in peanut butter."],
  },
  {
    mealType: "snack",
    name: "Carrot Sticks + Hummus",
    description: "Crunchy carrots with hummus.",
    calories: 140,
    prepTime: 5,
    servings: 1,
    tags: ["Crunchy", "Plant-Protein"],
    allergens: ["sesame"],
    diets: ["vegan", "vegetarian", "mediterranean"],
    ingredients: ["Carrot sticks", "Hummus"],
    instructions: ["Serve carrots with hummus."],
  },
  {
    mealType: "snack",
    name: "Greek Yogurt Cup",
    description: "Plain yogurt with cinnamon.",
    calories: 120,
    prepTime: 2,
    servings: 1,
    tags: ["Protein-Rich"],
    allergens: ["dairy"],
    diets: ["vegetarian", "highprotein"],
    ingredients: ["3/4 cup Greek yogurt", "Cinnamon"],
    instructions: ["Stir cinnamon into yogurt."],
  },
  {
    mealType: "snack",
    name: "Trail Mix",
    description: "Nuts + seeds + dried fruit.",
    calories: 210,
    prepTime: 2,
    servings: 1,
    tags: ["Energy", "Portable"],
    allergens: ["nuts"],
    diets: ["vegetarian"],
    ingredients: ["Almonds", "Cashews", "Pumpkin seeds", "Cranberries"],
    instructions: ["Mix and enjoy."],
  },
];

export const recipeDb: Record<MealType, MealRecipe[]> = {
  breakfast: breakfasts,
  lunch: lunches,
  dinner: dinners,
  snack: snacks,
};

